### ISSUE TITLE
Run app unsuccessfully - how do I enter the app itself?

### ISSUE THREAD

**Issue by aviv12825** [oracle-devrel/oci-generative-ai-jet-ui#11]
![server](https://github.com/oracle-devrel/oci-generative-ai-jet-ui/assets/29521767/03325911-68c2-4f2e-a757-f28e281cacb2)
![client](https://github.com/oracle-devrel/oci-generative-ai-jet-ui/assets/29521767/d49faee5-dd6a-4041-a1e8-1064ec3eebc8)

I follow your readme file and run the command "python3 server.py" (no output after this command) and also run "npx ojet build web" (got success: build finished").

How do I enter the app itself ? 
Attached pictures as well

Please advise

**Comment by WSPluta** [comment]
hey @aviv12825 

By running build you will compile the application and you can point your webserver from web/ dir

You can also run `npx ojet serve` instead of build to run the app locally.
