### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by palaneandavar** [oracle-devrel/oci-generative-ai-jet-ui#22]
Hi

We followed the complete process as mentioned in the document and installed the latest nodejs and jet, but it is not connecting and not working  from the fort end UI from the backend API. It works 
![GEN_AI_not_providing_output](https://github.com/user-attachments/assets/5b9fec97-bdd6-478b-ab7c-4df64cb5c4c3)

We are able to test the genAI API with the python script and we had imported and upgraded the OCI package but still it is not working
====
 npm install

up to date, audited 352 packages in 4s

42 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
=====
(ociaivenv) [oracle@omoic-genai app]$ npm audit
# npm audit report

requirejs  <=2.3.6
Severity: high
jrburke requirejs vulnerable to prototype pollution - https://github.com/advisories/GHSA-x3m3-4wpv-5vgc
No fix available
node_modules/requirejs
  @oracle/oraclejet  *
  Depends on vulnerable versions of requirejs
  node_modules/@oracle/oraclejet
    @oracle/oraclejet-core-pack  *
    Depends on vulnerable versions of @oracle/oraclejet
    Depends on vulnerable versions of @oracle/oraclejet-webdriver
    node_modules/@oracle/oraclejet-core-pack
    @oracle/oraclejet-webdriver  >=14.0.0
    Depends on vulnerable versions of @oracle/oraclejet
    node_modules/@oracle/oraclejet-webdriver

4 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.
=====
(ociaivenv) [oracle@omoic-genai app]$  npm audit fix --force
npm warn using --force Recommended protections disabled.
npm warn audit No fix available for @oracle/oraclejet@*
npm warn audit No fix available for @oracle/oraclejet-core-pack@*

up to date, audited 352 packages in 6s

42 packages are looking for funding
  run `npm fund` for details

# npm audit report

requirejs  <=2.3.6
Severity: high
jrburke requirejs vulnerable to prototype pollution - https://github.com/advisories/GHSA-x3m3-4wpv-5vgc
No fix available
node_modules/requirejs
  @oracle/oraclejet  *
  Depends on vulnerable versions of requirejs
  node_modules/@oracle/oraclejet
    @oracle/oraclejet-core-pack  *
    Depends on vulnerable versions of @oracle/oraclejet
    Depends on vulnerable versions of @oracle/oraclejet-webdriver
    node_modules/@oracle/oraclejet-core-pack
    @oracle/oraclejet-webdriver  >=14.0.0
    Depends on vulnerable versions of @oracle/oraclejet
    node_modules/@oracle/oraclejet-webdriver

4 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.
==================
(ociaivenv) [oracle@omoic-genai app]$ npx ojet serve
Warning: Command is missing platform. Default to web.
Build: true
BuildType: dev
Destination: undefined
Destination target: undefined
Livereload: true
Watch files: true
Livereload port: 35729
Platform: web
Port: 8000
Theme: redwood
Theme platform: web
Theme version: 16.0.8
Building app.
Cleaning staging path.
Running before_build hook.
Copy files to staging directory.
Copy finished.
Copy library files to staging directory.
Copy finished.
Copy reference components to staging directory.
Copy finished.
Copy local web components
Copy local web components finished
Copied local resource components
Optimizing svg into SVG sprites.
Svg optimization task finished.
Running before_injection hook.
Running typescript injection tasks.
Task typescript injection finished.
Compile application typescript
Running before_app_typescript hook.
Running after_app_typescript hook.
Compile application typescript finished
Compiling sass...
Sass compile finished.
Running theme injection task.
Task index.html theme path injection finished.
Running theme copy task.
Theme copy task finished.
Task index.html script injection finished
Running injection tasks.
Task main.js paths injection finished.
runAllComponentHooks
runAllComponentHooks for component: web/components/md-wrapper/1.0.0/component.json
Running after_component_build hook.
runAllComponentHooks for component: web/components/md-wrapper/1.0.0/component.json finished
runAllComponentHooks for component: web/components/oj-ref-marked/4.3.0/component.json
Running after_component_build hook.
runAllComponentHooks for component: web/components/oj-ref-marked/4.3.0/component.json finished
runAllComponentHooks for component: web/components/oj-sample/9.0.0/component.json
Running after_component_build hook.
runAllComponentHooks for component: web/components/oj-sample/9.0.0/component.json finished
Running after_build hook.
Running before_serve hook.
Starting web server.
Connecting to http://localhost:8000
Running after_serve hook.
Success: Server ready: http://localhost:8000
Listening on port 35729.
Starting watcher.
Watching files.
Watching Interval: 1000.
Watcher: sass is ready.
Watcher: sourceFiles is ready.
Watcher: themes is ready.
==============

but after this the data is not provided by the output and it takes huge time and even after 1 hour it does not provide the result

**Comment by peppertech** [comment]
The browser console should provide a lot of error information.  Can you please provide what is being shown there.

**Comment by palaneandavar** [comment]
Trying to open a WebSocket connection...
index.tsx:150 summary loading
index.tsx:48 WebSocket connection to 'ws://10.19.3.102:1986/' failed: 
initWebSocket @ index.tsx:48Understand this error
index.tsx:107 Connection closed
index.tsx:47 Trying to open a WebSocket connection...
index.tsx:48 WebSocket connection to 'ws://10.19.3.102:1986/' failed: 
initWebSocket @ index.tsx:48Understand this error
index.tsx:107 Connection closed
====

but the server  had been started (venv) [oracle@omoic-genai python]$ python3 server.py

**Comment by palaneandavar** [comment]
index.tsx:48 WebSocket connection to 'ws://10.19.3.102:1986/' failed: 
initWebSocket @ index.tsx:48
(anonymous) @ index.tsx:141
A @ index.js:478
T @ index.js:417
callback @ ojvcomponent.js:1154Understand this error
index.tsx:107 Connection closed
chat.tsx:42 lastKey before set:  -1
index.tsx:196 WebSocket is already in CLOSING or CLOSED state.
(anonymous) @ index.tsx:196
setTimeout
handleQuestionChange @ index.tsx:195
H @ props.js:141
(anonymous) @ ojvcomponent.js:722Understand this error
index.tsx:47 Trying to open a WebSocket connection...
index.tsx:48 WebSocket connection to 'ws://10.19.3.102:1986/' failed: 
initWebSocket @ index.tsx:48Understand this error
index.tsx:107 Connection closed
3index.tsx:47 Trying to open a WebSocket connection...
index.tsx:48 WebSocket connection to 'ws://10.19.3.102:1986/' failed: 
initWebSocket @ index.tsx:48Understand this error
index.tsx:107 Connection closed
index.tsx:110 WebSocket connection to 'ws://10.19.3.102:1986/' failed: WebSocket is closed before the connection is established.
onClose @ index.tsx:110Understand this warning
index.tsx:48 WebSocket connection to 'ws://10.19.3.102:1986/' failed: 
initWebSocket @ index.tsx:48Understand this error
index.tsx:107 Connection closed

**Comment by palaneandavar** [comment]
[oracle@omoic-genai ~]$ wscat -c ws://10.19.3.102:1986/
error: connect ECONNREFUSED 10.19.3.102:1986
> [oracle@omoic-genai ~]$
=== 
within the same server in the server we had got the me error

**Comment by palaneandavar** [comment]
[root@omoic-genai home]# sudo netstat -tuln | grep 1986
tcp        0      0 127.0.0.1:1986          0.0.0.0:*               LISTEN
[root@omoic-genai home]#
---- it is listening in localhost not with the ip

**Comment by palaneandavar** [comment]
summary loading
index.tsx:95 Connection opened
chat.tsx:42 lastKey before set:  0
index.tsx:47 Trying to open a WebSocket connection...
index.tsx:142 Running Gen AI
index.tsx:95 Connection opened
2chat.tsx:42 lastKey before set:  -1
index.tsx:107 Connection closed

**Comment by palaneandavar** [comment]
when we changed the IP to 0.0.0.0 then it started working but when we are trying to get the answer it does not provide and it gives the error message
![image](https://github.com/user-attachments/assets/61233355-c531-499a-8025-779c82c5352c)

**Comment by palaneandavar** [comment]
[oracle@omoic-genai ~]$ wscat -c ws://10.19.3.102:1986
Connected (press CTRL+C to quit)
> {"prompt": "Tell me about Oracle EBS"}
Disconnected (code: 1011, reason: "")
===
when we enter it gives the error connection closed

**Comment by palaneandavar** [comment]
Connection closed: received 1001 (going away); then sent 1001 (going away)
Not using Expect header...
send: b'POST /20231130/actions/generateText HTTP/1.1\r\nuser-agent: Oracle-PythonSDK/2.126.2 (python 3.11.9; x86_64-Linux)\r\naccept-encoding: gzip, deflate\r\naccept: application/json, text/event-stream\r\nconnection: keep-alive\r\ncontent-type: application/json\r\nopc-client-info: Oracle-PythonSDK/2.126.2\r\nopc-request-id: 169D8C97F943473D90B10BC162E8E4BD\r\nContent-Length: 414\r\ndate: Fri, 02 Aug 2024 21:01:18 GMT\r\nhost: inference.generativeai.us-chicago-1.oci.oraclecloud.com\r\nx-content-sha256: tzOvMmEXrLBuJ6Rm33vFgz/Y1JTQlHj2T2Rg1KKdB5o=\r\nauthorization: Signature algorithm="rsa-sha256",headers="date (request-target) host content-length content-type x-content-sha256",keyId="ocid1.tenancy.oc1..aaaaaaaakxtqatkulodfc6i4jptp7uroq2pkzejm5hrqml33f4s7fd246btq/ocid1.user.oc1..aaaaaaaanpdqo2dymynrrnmpbrwvb6bleaju2j6pdhttcxeohwp5l6n7qbza/85:80:0a:43:bd:f9:29:2b:1b:a4:65:7d:d0:e8:1c:10",signature="sHoB9CKp0rRDg8lwyS0V39oX98C6IplcBwR3dyZlkvOnQw71AfdZ3VBg96kkPd2extp6OBb15MqITjeCTbT4o8ZwEhl5Otb4oN5VwQBS53GlQd3oIdoM+GrTh5aKNJ5whLyPpPqcV+5UlCoaCSn1OTFGnfPX0Qm7OQ1vufYaemiEAUabNJZ5mTgZiapgxCCKu5I3rir2RHPLm0jsKUE8+CTIujQeBgoBozqxwdSfnaqh4pRxz9rrHLrJTxEe21erudUiiCvF1ga4KDkZwfbl3H7OZr8Drrh01hGscEN9tTO5mB/2nhaL4GFyNa1GNrQ0YymCKom+eSqazFR05XEZ/A==",version="1"\r\n\r\n{"compartmentId": "ocid1.compartment.oc1..aaaaaaaahq4wcpqwpug5z2se3uolpm7sk4dgql2vadves7vivmoi6bzujioa", "servingMode": {"servingType": "DEDICATED", "endpointId": "ocid1.generativeaiendpoint.oc1.us-chicago-1.amaaaaaaeras5xiavrsefrftfupp42lnniddgjnxuwbv5jypl64i7ktan65a"}, "inferenceRequest": {"runtimeType": "COHERE", "prompt": "ebs ", "maxTokens": 1000, "temperature": 0.75, "topP": 0.7, "frequencyPenalty": 1.0}}'
reply: 'HTTP/1.1 404 Not Found\r\n'
header: content-type: application/json
header: opc-request-id: 169D8C97F943473D90B10BC162E8E4BD/10B9C6D7821A1E8D8D59B36B718C70D9/E3F995E04D9CDAE24B2ED55423488BB1
header: content-encoding: gzip
header: content-length: 102
connection handler failed
Traceback (most recent call last):
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/server.py", line 110, in handle_websocket
    response = await generate_ai_response(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/throttler/decorators.py", line 14, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/server.py", line 50, in generate_ai_response
    generate_text_response = generative_ai_inference_client.generate_text(generate_text_detail)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/oci/generative_ai_inference/generative_ai_inference_client.py", line 398, in generate_text
    return retry_strategy.make_retrying_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/oci/retry/retry.py", line 238, in make_retrying_call
    return func_ref(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/oci/base_client.py", line 535, in call_api
    response = self.request(request, allow_control_chars, operation_name, api_reference_link)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/circuitbreaker.py", line 159, in wrapper
    return call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/circuitbreaker.py", line 170, in call
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/oci/base_client.py", line 726, in request
    self.raise_service_error(request, response, service_code, message, operation_name, api_reference_link, target_service, request_endpoint, client_version, timestamp, deserialized_data)
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/oci/base_client.py", line 891, in raise_service_error
    raise exceptions.ServiceError(
oci.exceptions.ServiceError: {'target_service': 'generative_ai_inference', 'status': 404, 'code': '404', 'opc-request-id': '169D8C97F943473D90B10BC162E8E4BD/10B9C6D7821A1E8D8D59B36B718C70D9/E3F995E04D9CDAE24B2ED55423488BB1', 'message': 'Authorization failed or requested resource not found.', 'operation_name': 'generate_text', 'timestamp': '2024-08-02T21:01:19.002467+00:00', 'client_version': 'Oracle-PythonSDK/2.126.2', 'request_endpoint': 'POST https://inference.generativeai.us-chicago-1.oci.oraclecloud.com/20231130/actions/generateText', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_404 for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/generative-ai-inference/20231130/GenerateTextResult/GenerateText for details on this operation's requirements. If you are unable to resolve this generative_ai_inference issue, please contact Oracle support and provide them this full error message."}
Connection closed: received 1001 (going away); then sent 1001 (going away)
Connection closed: received 1005 (no status received [internal]); then sent 1005 (no status received [internal])
connection handler failed
Traceback (most recent call last):
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/server.py", line 107, in handle_websocket
    if objData.msgType == "question":
       ^^^^^^^^^^^^^^^
AttributeError: 'types.SimpleNamespace' object has no attribute 'msgType'
connection handler failed
Traceback (most recent call last):
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/server.py", line 106, in handle_websocket
    objData = json.loads(data,object_hook=lambda d: SimpleNamespace(**d))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----server.py has this logs

**Comment by palaneandavar** [comment]
Hi

Any update on this still getting the same issue 

(venv) [oracle@omoic-genai python]$ python server.py
Not using Expect header...
send: b'POST /20231130/actions/generateText HTTP/1.1\r\nuser-agent: Oracle-PythonSDK/2.130.0 (python 3.11.9; x86_64-Linux)\r\naccept-encoding: gzip, deflate\r\naccept: application/json, text/event-stream\r\nconnection: keep-alive\r\ncontent-type: application/json\r\nopc-client-info: Oracle-PythonSDK/2.130.0\r\nopc-request-id: B99590CE006841808319A5C4ADE7F000\r\nContent-Length: 412\r\ndate: Sun, 04 Aug 2024 09:05:43 GMT\r\nhost: inference.generativeai.us-chicago-1.oci.oraclecloud.com\r\nx-content-sha256: ZcZ2GEud0HlKFx0J0tZfSbpyoetyS1aDxVCrs2kOdzs=\r\nauthorization: Signature algorithm="rsa-sha256",headers="date (request-target) host content-length content-type x-content-sha256",keyId="ocid1.tenancy.oc1..aaaaaaaakxtqatkulodfc6i4jptp7uroq2pkzejm5hrqml33f4s7fd246btq/ocid1.user.oc1..aaaaaaaanpdqo2dymynrrnmpbrwvb6bleaju2j6pdhttcxeohwp5l6n7qbza/85:80:0a:43:bd:f9:29:2b:1b:a4:65:7d:d0:e8:1c:10",signature="VbxHEqb3KkKA1WElp6IjOrqOIzXs1uQ/2t5XM+MKcYjJaGE1aahRuOHO7E6r5H/uMYyZ7VeUQ07xvgg8gY0RpXTgcUwsAWjU4fRlV99H01D1MmLNNPMWGVJWQ7xhJPSAlItdoECGP3xAX9crqjl5mMYTA1MpwEfHveqzcBI2ldQPc2IIoMwMvQCVsDiqTWMDqCr9vpQl9lmwNTbGG5GI65fKft3a2ApzR9lRVW8iRRdlNEPat8hwyHpE/tjKtAqAHvrse5p+wF9CSQa9gnpgn1iFJLyVDDS+B1siVo0acPSI7ij0y4/WWlFnObn4arA1f3MeUe06qxmiNc30FQaRYQ==",version="1"\r\n\r\n{"compartmentId": "ocid1.compartment.oc1..aaaaaaaahq4wcpqwpug5z2se3uolpm7sk4dgql2vadves7vivmoi6bzujioa", "servingMode": {"servingType": "DEDICATED", "endpointId": "ocid1.generativeaiendpoint.oc1.us-chicago-1.amaaaaaaeras5xiavrsefrftfupp42lnniddgjnxuwbv5jypl64i7ktan65a"}, "inferenceRequest": {"runtimeType": "COHERE", "prompt": "hi", "maxTokens": 1000, "temperature": 0.75, "topP": 0.7, "frequencyPenalty": 1.0}}'
reply: 'HTTP/1.1 404 Not Found\r\n'
header: content-type: application/json
header: opc-request-id: B99590CE006841808319A5C4ADE7F000/495789D996C307535167D2D7C86016EF/DD6DD241852130E4ADCA91463B8E19C7
header: content-encoding: gzip
header: content-length: 102
connection handler failed
Traceback (most recent call last):
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/server.py", line 102, in handle_websocket
    response = await generate_ai_response(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/throttler/decorators.py", line 14, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/server.py", line 46, in generate_ai_response
    generate_text_response = generative_ai_inference_client.generate_text(generate_text_detail)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/oci/generative_ai_inference/generative_ai_inference_client.py", line 395, in generate_text
    return retry_strategy.make_retrying_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/oci/retry/retry.py", line 238, in make_retrying_call
    return func_ref(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/oci/base_client.py", line 535, in call_api
    response = self.request(request, allow_control_chars, operation_name, api_reference_link)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/circuitbreaker.py", line 159, in wrapper
    return call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/circuitbreaker.py", line 170, in call
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/oci/base_client.py", line 726, in request
    self.raise_service_error(request, response, service_code, message, operation_name, api_reference_link, target_service, request_endpoint, client_version, timestamp, deserialized_data)
  File "/u01/app/product/oci-generative-ai-jet-ui/service/python/venv/lib64/python3.11/site-packages/oci/base_client.py", line 891, in raise_service_error
    raise exceptions.ServiceError(
oci.exceptions.ServiceError: {'target_service': 'generative_ai_inference', 'status': 404, 'code': '404', 'opc-request-id': 'B99590CE006841808319A5C4ADE7F000/495789D996C307535167D2D7C86016EF/DD6DD241852130E4ADCA91463B8E19C7', 'message': 'Authorization failed or requested resource not found.', 'operation_name': 'generate_text', 'timestamp': '2024-08-04T09:05:44.939568+00:00', 'client_version': 'Oracle-PythonSDK/2.130.0', 'request_endpoint': 'POST https://inference.generativeai.us-chicago-1.oci.oraclecloud.com/20231130/actions/generateText', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_404 for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/generative-ai-inference/20231130/GenerateTextResult/GenerateText for details on this operation's requirements. If you are unable to resolve this generative_ai_inference issue, please contact Oracle support and provide them this full error message."}

--- comment out the compartment id check from the server.py but still the same issue ,when we write a just a python script to access it works but it does not work with this application

**Comment by peppertech** [comment]
The error you are getting is a 404 error which tells me that you still have something off with the hostname or path.

I just re-ran the code from a fresh clone and it is running correctly as long as you have the configurations done properly.

I would recommend that you start a new clone of the project, and only update the oci config and the compartment_id value.  Leave everything else the same and see if that will work.

**Comment by WSPluta** [comment]
@palaneandavar let me know how you getting on, did you managed to get it working?

**Comment by peppertech** [comment]
Closing issue as there hasn't been a response in a week.  Please feel free to reopen if the issue still exists.
